import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, MapPin, CalendarDays, Bell, Plus, Star, Users, X, SlidersHorizontal, ChevronDown, Heart, BriefcaseBusiness, WalletCards, House, Dumbbell, ArrowRight, BadgeCheck, Sparkles, Menu} from 'lucide-react';
import './styles.css';

const CATS={all:{label:'全部',icon:Sparkles,color:'#ff6b4a'},business:{label:'事業',icon:BriefcaseBusiness,color:'#2b4c7e'},wealth:{label:'財富',icon:WalletCards,color:'#10b981'},family:{label:'家庭',icon:House,color:'#f59e0b'},relationships:{label:'感情',icon:Heart,color:'#ec4899'},health:{label:'健康',icon:Dumbbell,color:'#14b8a6'}};
const photos=['photo-1521737711867-e3b97375f902','photo-1551836022-d5d88e9218df','photo-1516321318423-f06f85e504b3','photo-1529156069898-49953e39b3ac','photo-1511632765486-a01980e01a18','photo-1529156069898-49953e39b3ac','photo-1556761175-b413da4baf72','photo-1454165804606-c3d57bc86b40','photo-1500530855697-b586d89ba3ee','photo-1518611012118-696072aa579a'];
const names=['Mina','Kevin','Ivy','Ryan','Claire','Jason','Sophia','Daniel','Emma','Leo'];
const seed=[
 ['創業者週末早餐會｜從 0 到 1 的產品思維','business','2026/08/15 10:00','台北市大安區',false,350,8,12,['創業交流','產品策略']],
 ['AI 時代的職涯加速工作坊','business','2026/08/19 19:30','Google Meet',true,'免費',21,30,['職涯成長','AI']],
 ['小資族 ETF 入門：打造第一份被動收入','wealth','2026/08/16 14:00','台北市信義區',false,500,11,16,['理財新手','ETF']],
 ['現金流桌遊夜｜邊玩邊學財商','wealth','2026/08/22 19:00','新北市板橋區',false,300,6,8,['財商','桌遊']],
 ['親子共讀野餐日：讓故事走進生活','family','2026/08/17 09:30','台北市大安森林公園',false,'免費',9,15,['親子時光','戶外']],
 ['新手爸媽的情緒教養練習室','family','2026/08/24 15:00','Google Meet',true,200,18,20,['親職教育','溝通']],
 ['不尷尬深度交友｜城市散步小聚','relationships','2026/08/16 16:30','台北市中山區',false,250,7,10,['認識新朋友','城市散步']],
 ['關係經營讀書會：好好說出需要','relationships','2026/08/21 19:30','台中市西區',false,'免費',12,12,['感情經營','讀書會']],
 ['晨光河濱慢跑｜5K 零壓力社群跑','health','2026/08/18 06:30','台北市大佳河濱公園',false,'免費',14,25,['週末健身','跑步']],
 ['下班瑜珈伸展：釋放肩頸壓力','health','2026/08/20 19:00','新竹市東區',false,450,5,10,['瑜珈','身心平衡']],
].map((e,i)=>({id:String(i+1),title:e[0],category:e[1],coverImg:`https://images.unsplash.com/${photos[i]}?auto=format&fit=crop&w=900&q=82`,host:{name:names[i],avatar:`https://i.pravatar.cc/120?img=${i+12}`,rating:(4.7+(i%3)*.1).toFixed(1)},dateTime:e[2],location:e[3],isOnline:e[4],price:e[5],currentParticipants:e[6],maxParticipants:e[7],tags:e[8],description:'這是一場重視真實交流與行動收穫的小型聚會。主辦人會用輕鬆的引導，讓每位參與者都能自在分享、帶走可實踐的新觀點，並認識同頻的夥伴。'}));

function Modal({children,onClose,wide=false}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={'modal '+(wide?'wide':'')}><button className="close" onClick={onClose}><X/></button>{children}</div></div>}
function App(){
 const [category,setCategory]=useState('all'),[query,setQuery]=useState(''),[place,setPlace]=useState('全部地點'),[event,setEvent]=useState(null),[create,setCreate]=useState(false),[mobile,setMobile]=useState(false),[toast,setToast]=useState('');
 const filtered=useMemo(()=>seed.filter(e=>(category==='all'||e.category===category)&&(!query||[e.title,e.location,...e.tags,e.host.name].join(' ').toLowerCase().includes(query.toLowerCase()))&&(place==='全部地點'||(place==='線上'?e.isOnline:e.location.includes(place)))),[category,query,place]);
 const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2300)};
 return <div>
  <header><div className="nav"><a className="brand" href="#"><span className="logo"><Users/></span><b>Life<span>Gether</span></b></a><nav className={mobile?'open':''}>{Object.entries(CATS).map(([k,c])=>{const I=c.icon;return <button key={k} className={category===k?'active':''} onClick={()=>{setCategory(k);setMobile(false)}} style={{'--accent':c.color}}><I/> {c.label}</button>})}</nav><div className="user"><button className="create" onClick={()=>setCreate(true)}><Plus/>發起活動</button><button className="icon"><Bell/><i/></button><img src="https://i.pravatar.cc/80?img=47"/><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button></div></div>
  <div className="searchbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋活動、關鍵字或地點..."/></label><select><option>任何日期</option><option>本週</option><option>本月</option></select><select value={place} onChange={e=>setPlace(e.target.value)}><option>全部地點</option><option>台北市</option><option>台中市</option><option>新竹市</option><option>新北市</option><option>線上</option></select><select><option>所有費用</option><option>免費</option><option>付費</option></select><button className="filter"><SlidersHorizontal/>進階篩選</button></div></header>
  <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles/>超過 12,000 位夥伴正在相聚</span><h1>找到你的同好圈，<br/><em>全方位升級</em>你的人生</h1><p>從事業到健康，加入一場真誠的聚會，讓每一次相遇都成為向前的力量。</p><div><button className="hero-cta" onClick={()=>document.querySelector('#events').scrollIntoView({behavior:'smooth'})}>探索聚會 <ArrowRight/></button><span className="trust"><b>4.9</b> 平均活動評分</span></div></div><div className="hero-card"><img src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1100&q=85"/><span className="spot">本週精選</span><div><small>感情 · 城市散步</small><h3>不尷尬深度交友小聚</h3><p><CalendarDays/> 8/16 週日 · 台北中山</p></div></div></section>
  <section className="content" id="events"><div className="feed"><div className="section-title"><div><span>為你精選</span><h2>{CATS[category].label}聚會</h2></div><p>共 {filtered.length} 場活動</p></div>{filtered.length?<div className="grid">{filtered.map(e=><EventCard key={e.id} e={e} onClick={()=>setEvent(e)}/>)}</div>:<div className="empty"><Search/><h3>找不到符合的活動</h3><p>換個關鍵字或清除篩選條件再看看。</p><button onClick={()=>{setQuery('');setCategory('all');setPlace('全部地點')}}>清除篩選</button></div>}</div>
  <aside><section><div className="aside-head"><h3>人氣主辦人</h3><button>查看全部</button></div>{seed.slice(0,3).map((e,i)=><div className="host" key={e.id}><img src={e.host.avatar}/><div><b>{e.host.name} {i<2&&<BadgeCheck/>}</b><small>{CATS[e.category].label}領域 · ⭐ {e.host.rating}</small></div><button onClick={()=>flash(`已追蹤 ${e.host.name}`)}>追蹤</button></div>)}</section><section><h3>熱門探索</h3><div className="tags">{['創業交流','理財新手','週末健身','感情經營','親子時光','城市散步'].map(t=><button onClick={()=>setQuery(t)} key={t}>#{t}</button>)}</div></section><section className="verify"><BadgeCheck/><div><b>安心參加每場聚會</b><p>實名認證、活動評價與社群守則，共同守護每次相遇。</p><a href="#">了解安全機制 <ArrowRight/></a></div></section></aside></section>
  </main><footer><b>LifeGether</b><span>把想過的人生，和對的人一起實現。</span><div>社群守則　 主辦人認證　 隱私政策　 © 2026 LifeGether</div></footer>
  {event&&<Modal wide onClose={()=>setEvent(null)}><div className="detail"><img className="detail-cover" src={event.coverImg}/><div className="detail-body"><span className="pill" style={{background:CATS[event.category].color}}>{CATS[event.category].label}</span><h2>{event.title}</h2><div className="detail-host"><img src={event.host.avatar}/><div><b>{event.host.name} <BadgeCheck/></b><small>認證主辦人 · ⭐ {event.host.rating}</small></div></div><p className="desc">{event.description}</p><div className="facts"><p><CalendarDays/><span><small>時間</small>{event.dateTime}</span></p><p><MapPin/><span><small>地點</small>{event.location}</span></p><p><WalletCards/><span><small>費用</small>{event.price==='免費'?'免費':`NT$ ${event.price}`}</span></p></div><div className="apply"><div><small>目前報名</small><b>{event.currentParticipants} / {event.maxParticipants} 人</b></div><button disabled={event.currentParticipants===event.maxParticipants} onClick={()=>{flash('已送出報名申請！');setEvent(null)}}>{event.currentParticipants===event.maxParticipants?'候補登記':'申請報名'}</button></div></div></div></Modal>}
  {create&&<Modal onClose={()=>setCreate(false)}><CreateForm onDone={()=>{setCreate(false);flash('活動草稿已建立！')}}/></Modal>}{toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
function EventCard({e,onClick}){const c=CATS[e.category],full=e.currentParticipants===e.maxParticipants;return <article className="card" onClick={onClick} tabIndex="0"><div className="cover"><img src={e.coverImg}/><span className="pill" style={{background:c.color}}>{c.label}</span><span className={'status '+(full?'full':'')}>{full?'已額滿':'報名中'}</span><button className="save" onClick={x=>x.stopPropagation()}><Heart/></button></div><div className="card-body"><div className="card-host"><img src={e.host.avatar}/><span>by <b>{e.host.name}</b> · ⭐ {e.host.rating}</span></div><h3>{e.title}</h3><p><CalendarDays/> {e.dateTime}</p><p><MapPin/> {e.location} {e.isOnline&&<em>線上</em>}</p><p><WalletCards/> {e.price==='免費'?<strong>免費</strong>:`NT$ ${e.price}`}</p><div className="progress"><div><span>已有 {e.currentParticipants} 人參加</span><b>{e.currentParticipants}/{e.maxParticipants}</b></div><i><span style={{width:`${e.currentParticipants/e.maxParticipants*100}%`,background:c.color}}/></i></div><div className="card-foot"><div className="avatars">{[1,2,3].map((n,i)=><img key={i} src={`https://i.pravatar.cc/50?img=${Number(e.id)*3+n}`}/>)}<span>+{Math.max(0,e.currentParticipants-3)}</span></div><button>{full?'查看詳情':'我要報名'} <ArrowRight/></button></div></div></article>}
function CreateForm({onDone}){const [step,setStep]=useState(1),[cat,setCat]=useState('');return <div className="create-form"><span className="eyebrow">建立新聚會</span><h2>{step===1?'這場聚會，想讓哪個面向更好？':'補上活動基本資訊'}</h2><p>{step===1?'先選擇一個核心領域，讓同頻的人更容易找到你。':'之後仍可在主辦人後台繼續編輯。'}</p>{step===1?<div className="cat-pick">{Object.entries(CATS).filter(([k])=>k!=='all').map(([k,c])=>{const I=c.icon;return <button className={cat===k?'picked':''} onClick={()=>setCat(k)} style={{'--accent':c.color}} key={k}><I/><b>{c.label}</b><small>探索{c.label}的新可能</small></button>})}</div>:<div className="fields"><label>活動名稱<input placeholder="例如：週末創業者早餐會"/></label><div><label>日期<input type="date"/></label><label>時間<input type="time"/></label></div><label>地點<input placeholder="輸入地址或線上會議連結"/></label><label>活動簡介<textarea placeholder="告訴大家這場活動會做什麼..."/></label></div>}<button className="next" disabled={!cat} onClick={()=>step===1?setStep(2):onDone()}>{step===1?'下一步':'建立活動草稿'} <ArrowRight/></button></div>}
createRoot(document.getElementById('root')).render(<App/>);
